"""insight key and pinned memory

Revision ID: 4ef6ad8d77ed
Revises: bb0694989a08
Create Date: 2026-09-22 11:30:39.883338
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "4ef6ad8d77ed"
down_revision: str | None = "bb0694989a08"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("marketing_insights", sa.Column("key", sa.String(length=120), nullable=True))
    op.create_index(op.f("ix_marketing_insights_key"), "marketing_insights", ["key"], unique=False)
    op.add_column(
        "marketing_memory",
        sa.Column("pinned", sa.Boolean(), server_default=sa.text("false"), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("marketing_memory", "pinned")
    op.drop_index(op.f("ix_marketing_insights_key"), table_name="marketing_insights")
    op.drop_column("marketing_insights", "key")
    # ### end Alembic commands ###
