"""publication provider state

Revision ID: bb0694989a08
Revises: 9475fda3058b
Create Date: 2026-09-22 06:53:54.583875
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "bb0694989a08"
down_revision: str | None = "9475fda3058b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "publications",
        sa.Column(
            "provider_state",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("publications", "provider_state")
    # ### end Alembic commands ###
