"""content versions and ai cache

Revision ID: 9475fda3058b
Revises: 81aa5166f148
Create Date: 2026-09-21 19:17:01.577190
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "9475fda3058b"
down_revision: str | None = "81aa5166f148"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_response_cache",
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("provider", sa.String(length=48), nullable=False),
        sa.Column("model", sa.String(length=120), nullable=False),
        sa.Column(
            "response",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_ai_response_cache_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_response_cache")),
        sa.UniqueConstraint("workspace_id", "fingerprint", name="uq_ai_cache_ws_fp"),
    )
    op.create_index(
        op.f("ix_ai_response_cache_expires_at"), "ai_response_cache", ["expires_at"], unique=False
    )
    op.create_table(
        "content_versions",
        sa.Column("content_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("reason", sa.String(length=32), nullable=False),
        sa.Column(
            "snapshot",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["content_id"],
            ["contents.id"],
            name=op.f("fk_content_versions_content_id_contents"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_content_versions_created_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_content_versions")),
        sa.UniqueConstraint("content_id", "version", name="uq_content_version"),
    )
    op.create_index(
        op.f("ix_content_versions_content_id"), "content_versions", ["content_id"], unique=False
    )
    op.add_column("ai_usage", sa.Column("request_fingerprint", sa.String(length=64), nullable=True))
    op.create_index(
        op.f("ix_ai_usage_request_fingerprint"), "ai_usage", ["request_fingerprint"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ai_usage_request_fingerprint"), table_name="ai_usage")
    op.drop_column("ai_usage", "request_fingerprint")
    op.drop_index(op.f("ix_content_versions_content_id"), table_name="content_versions")
    op.drop_table("content_versions")
    op.drop_index(op.f("ix_ai_response_cache_expires_at"), table_name="ai_response_cache")
    op.drop_table("ai_response_cache")
    # ### end Alembic commands ###
