"""Phase 3 browser checks: AI draft, editing, approval, scheduling, calendar drag, versions.

Run against a running stack (worker included):  python3 e2e/make_fixtures.py && python3 e2e/phase3.py
"""
import asyncio, os, re, sys, time, uuid
from datetime import datetime, timedelta
os.environ.setdefault("PLAYWRIGHT_BROWSERS_PATH", "/opt/pw-browsers")
from playwright.async_api import async_playwright, expect

BASE = os.environ.get("BASE_URL", "http://localhost:3000")
WORKER_LOG = os.environ.get("WORKER_LOG", "/tmp/worker.log")
FIX = os.environ.get("FIXTURES", "/tmp/e2e")
SHOTS = os.environ.get("SHOTS", "/tmp")
results = []

def check(name, ok, detail=""):
    results.append((name, ok)); print(("PASS " if ok else "FAIL ") + name + (f"  {detail}" if detail and not ok else ""))

def token_for(email, timeout=15):
    end = time.time() + timeout
    while time.time() < end:
        m = re.findall(rf"--- email to {re.escape(email)} ---.*?/verify-email\?token=([A-Za-z0-9_\-]+)", open(WORKER_LOG).read(), re.S)
        if m: return m[-1]
        time.sleep(0.5)

async def api(page, path, method="GET"):
    return await page.evaluate("""async ([p, m]) => { const r = await fetch('/api/v1' + p, {method: m}); return r.json(); }""", [path, method])

async def main():
    email = f"p3-{uuid.uuid4().hex[:8]}@example.com"
    async with async_playwright() as p:
        browser = await p.chromium.launch()
        ctx = await browser.new_context(bypass_csp=True, viewport={"width": 1440, "height": 950}, timezone_id="America/New_York")
        page = await ctx.new_page()
        errors = []
        page.on("pageerror", lambda e: errors.append(str(e)))

        await page.goto(f"{BASE}/register")
        await page.fill("#full_name", "Levan Beridze"); await page.fill("#email", email); await page.fill("#password", "espresso-before-eight")
        await page.click("button[type=submit]")
        await expect(page.get_by_text("Check your inbox")).to_be_visible()
        await page.goto(f"{BASE}/verify-email?token={token_for(email)}")
        await page.wait_for_url("**/onboarding")
        await page.fill("#biz-name", "Vake Roasters"); await page.fill("#biz-industry", "Coffee roastery")
        await page.click("text=Continue"); await expect(page.get_by_role("heading", name="Customers and goals")).to_be_visible()
        ws = (await api(page, "/workspaces"))[0]["id"]
        # Workspace time zone differs from the browser's on purpose.
        await page.evaluate("""async ([ws]) => {
          const csrf = document.cookie.split('; ').find(c => c.startsWith('cf_csrf=')).split('=')[1];
          await fetch(`/api/v1/workspaces/${ws}`, {method: 'PATCH', headers: {'content-type': 'application/json', 'x-csrf-token': decodeURIComponent(csrf)}, body: JSON.stringify({timezone: 'Asia/Tbilisi'})});
        }""", [ws])

        # A photo tagged so the agent can pick it
        await page.goto(f"{BASE}/media")
        await page.set_input_files("input[type=file]", f"{FIX}/teal.png")
        await expect(page.get_by_text("1 file")).to_be_visible(timeout=20000)
        await page.wait_for_function("[...document.querySelectorAll('main img')].some(i => i.complete && i.naturalWidth > 0)", timeout=20000)
        await page.get_by_role("button", name=re.compile("teal")).click()
        await page.fill("#media-tags", "cold"); await page.keyboard.press("Enter")
        await page.fill("#media-tags", "brew"); await page.keyboard.press("Enter")
        await page.get_by_role("button", name="Save", exact=True).click()
        await expect(page.get_by_role("dialog")).to_be_hidden()

        # Draft with AI
        await page.goto(f"{BASE}/content/new")
        await expect(page.get_by_text("AI drafts this month")).to_be_visible()
        check("development-mode notice shown", await page.get_by_text("offline test writer").count() > 0)
        await page.fill("#idea", "How we make cold brew")
        await page.get_by_role("button", name="Facebook").click()
        await page.get_by_role("button", name="Draft post").click()
        await page.wait_for_url(re.compile(r"/content/[0-9a-f-]{36}$"))
        await expect(page.get_by_role("tab", name="Facebook")).to_be_visible(timeout=20000)
        check("draft generated by worker and editor opened", True)
        post_id = page.url.rsplit("/", 1)[1]
        post = await api(page, f"/workspaces/{ws}/content/{post_id}")
        check("agent picked the tagged photo", len(post["media"]) == 1, str(post["media"]))
        await page.wait_for_function("[...document.querySelectorAll('aside img')].some(i => i.complete && i.naturalWidth > 0)", timeout=10000)
        await page.screenshot(path=f"{SHOTS}/p3_editor.png")

        # Edit Facebook caption, save (version bump)
        await page.get_by_role("tab", name="Facebook").click()
        await page.fill("#caption", "Eighteen hours, cold water, nothing else. Come taste the difference.")
        await page.click("text=Save changes")
        await expect(page.get_by_text("Version 2.")).to_be_visible()
        check("edit saved as a new version", True)

        # Approve, then schedule in the workspace time zone
        await page.get_by_role("button", name="Approve").click()
        await expect(page.get_by_text("account connected", exact=False).first).to_be_visible()
        check("approval warns that no account is connected to publish to", True)
        day = (datetime.now() + timedelta(days=3)).strftime("%Y-%m-%d")
        await page.get_by_role("button", name="Schedule").click()
        await page.fill("input[type=datetime-local]", f"{day}T18:00")
        await page.get_by_role("button", name="Save", exact=True).click()
        await expect(page.get_by_role("dialog")).to_be_hidden()
        post = await api(page, f"/workspaces/{ws}/content/{post_id}")
        check("scheduled in workspace zone (18:00 Tbilisi = 14:00 UTC)", post["status"] == "scheduled" and post["schedule"]["scheduled_at"].startswith(f"{day}T14:00"), str(post["schedule"]))

        # Calendar: drag to the next day, time of day kept
        await page.goto(f"{BASE}/calendar")
        chip = page.locator(f"a[href='/content/{post_id}']").first
        await expect(chip).to_be_visible()
        next_day = (datetime.now() + timedelta(days=4))
        target = page.locator(f"[data-day='{next_day.strftime('%Y-%m-%d')}']")
        await page.screenshot(path=f"{SHOTS}/p3_calendar.png")
        await chip.drag_to(target)
        await page.wait_for_timeout(1200)
        post = await api(page, f"/workspaces/{ws}/content/{post_id}")
        check("drag to next day keeps 18:00 local", post["schedule"]["scheduled_at"].startswith(f"{next_day.strftime('%Y-%m-%d')}T14:00"), str(post["schedule"]))

        # Redraft with an instruction, then look at history and restore
        await page.goto(f"{BASE}/content/{post_id}")
        await page.get_by_role("button", name="Redraft").click()
        await page.fill("textarea", "shorter")
        await page.get_by_role("dialog").get_by_role("button", name="Redraft").click()
        await expect(page.get_by_role("tab", name="Instagram")).to_be_visible(timeout=20000)
        post = await api(page, f"/workspaces/{ws}/content/{post_id}")
        check("redraft sends it back for approval", post["status"] == "awaiting_approval", post["status"])
        await page.get_by_role("button", name="History").click()
        await expect(page.get_by_text("Before redraft")).to_be_visible()
        await page.get_by_role("dialog").get_by_role("button", name="Restore").last.click()
        await expect(page.get_by_role("dialog")).to_be_hidden()
        post = await api(page, f"/workspaces/{ws}/content/{post_id}")
        check("restore brought back the original draft", post["version"] >= 4 and "(shorter)" not in (post["hook"] or ""), post["hook"])

        usage = await api(page, f"/workspaces/{ws}/usage")
        check("usage counts 2 AI drafts", usage["ai_content"]["used"] == 2, str(usage["ai_content"]))

        await page.goto(f"{BASE}/content")
        await page.get_by_role("tab", name="Needs approval").click()
        await expect(page.locator(f"a[href='/content/{post_id}']")).to_be_visible()
        check("content list filters by approval state", True)

        await page.goto(f"{BASE}/dashboard")
        await expect(page.get_by_text("Upcoming")).to_be_visible()
        check("dashboard lists the scheduled post", await page.locator(f"a[href='/content/{post_id}']").count() >= 1)

        check("no uncaught page errors", not errors, "; ".join(errors[:3]))
        await browser.close()
    failed = [n for n, ok in results if not ok]
    print(f"\n{len(results) - len(failed)}/{len(results)} checks passed")
    sys.exit(1 if failed else 0)

asyncio.run(main())
